export const FETCH_DASHBOARD_TRANSACTIONS = {
    FETCH_DASHBOARD_TRANSACTIONS_REQUEST : 'FETCH_DASHBOARD_TRANSACTIONS_REQUEST',
    FETCH_DASHBOARD_TRANSACTIONS_SUCCESS : 'FETCH_DASHBOARD_TRANSACTIONS_SUCCESS',
    FETCH_DASHBOARD_TRANSACTIONS_ERROR : 'FETCH_DASHBOARD_TRANSACTIONS_ERROR',
}

export const UDPATE_DASHBOARD_TRANSACTIONS = {
    ADD_DASHBOARD_TRANSACTION : 'ADD_DASHBOARD_TRANSACTION',
    TOGGLE_TIMEFRAME: 'TOGGLE_TIMEFRAME',
}
