export const FETCH_BALANCE = {
    FETCH_BALANCE_DATA_REQUEST : 'FETCH_BALANCE_DATA_REQUEST',
    FETCH_BALANCE_DATA_SUCCESS: 'FETCH_BALANCE_DATA_SUCCESS',
    FETCH_BALANCE_DATA_ERROR: 'FETCH_BALANCE_DATA_ERROR',
}

export const UPDATE = {
    INITIALIZE_BALANCE: 'UPDATE_BALANCE',
}