export const FETCH_PRIMARY_TRANSACTIONS = {
    FETCH_PRIMARY_TRANSACTIONS_REQUEST : 'FETCH_PRIMARY_TRANSACTIONS_REQUEST',
    FETCH_PRIMARY_TRANSACTIONS_SUCCESS : 'FETCH_PRIMARY_TRANSACTIONS_SUCCESS',
    FETCH_PRIMARY_TRANSACTIONS_ERROR : 'FETCH_PRIMARY_TRANSACTIONS_ERROR',
}

export const UDPATE_PRIMARY_TRANSACTIONS = {
    ADD_PRIMARY_TRANSACTION : 'ADD_PRIMARY_TRANSACTION',    
    UPDATE_PRIMARY_TRANSACTION: 'UPDATE_PRIMARY_TRANSACTION',
    REMOVE_PRIMARY_TRANSACTION: 'REMOVE_PRIMARY_TRANSACTION'
}

