
export const FETCH_TAG = {
    FETCH_TAG_DATA_REQUEST : 'FETCH_TAG_DATA_REQUEST',
    FETCH_TAG_DATA_SUCCESS: 'FETCH_TAG_DATA_SUCCESS',
    FETCH_TAG_DATA_ERROR: 'FETCH_TAG_DATA_ERROR',
}

export const UPDATE_TAG = {
    CREATE_TAG: 'CREATE_TAG',
    DELETE_TAG: 'DELETE_TAG',
    MODIFY_TAG: 'MODIFY_TAG',
}