
export const FETCH_TAG = {
    FETCH_TAG_DATA_REQUEST : 'FETCH_TAG_DATA_REQUEST',
    FETCH_TAG_DATA_SUCCESS: 'FETCH_TAG_DATA_SUCCESS',
    FETCH_TAG_DATA_ERROR: 'FETCH_TAG_DATA_ERROR',
}

export const MANIPULATE = {
    ADD_TAG: 'ADD_TAG',
    DELETE_TAG: 'DELETE_TAG',
    UPDATE_TAG: 'UPDATE_TAG',
}