
export const FETCH_USERDOC = {
    FETCH_USERDOC_DATA_REQUEST: 'FETCH_USERDOC_DATA_REQUEST',
    FETCH_USERDOC_DATA_SUCCESS: 'FETCH_USERDOC_DATA_SUCCESS',
    FETCH_USERDOC_DATA_ERROR: "FETCH_USERDOC_DATA_ERROR",
}

export const UPDATE_USERDOC = {
    UPDATE_USERDOC_DATA : 'UPDATE_USERDOC_DATA',
    UPDATE_USERDOC_SETTINGS: 'UPDATE_USERDOC_SETTINGS'
}

