
export const FETCH_USERDOC = {
    FETCH_DATA_REQUEST: 'FETCH_DATA_REQUEST',
    FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
    FETCH_DATA_ERROR: "FETCH_DATA_ERROR",
}

export const UPDATE = {
    UPDATE_USER_DATA : 'UPDATE_USER_DATA',
}

